project_name: ${PROJECT_NAME:-idh-prediction}
region: ${REGION:-us-central1}
dataset_name: 'raw_data'
BigQuery:
  features_dataset: 'training_features'
  patient_demographics: 'patient-demographics'
  registration_data: 'registration-data'
  real_time_machine_data: 'real-time-machine-data'
  sessionized_machine_data: 'sessionized-machine-data'
storage:
  bucket: ${BUCKET:-idh-prototype-data}
  csv_prefix: "raw-data-csv"
  parquet_prefix: "raw-data-parquet"
model:
  name: ${MODEL_NAME:-idh-xgboost-model}
  endpoint_name: ${MODEL_ENDPOINT_NAME:-idh-endpoint}
  docker_image_uri: "us-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.2-1:latest"
  machine_type: "n1-standard-4"
  session_window: 12 # number of hours to look back for sessionization
  interval_time: 15 # in minutes
  idh_threshold: 90.0 # systolic blood pressure threshold for hypotension
  prediction_intervals: 5 # number of intervals to look ahead for hypotension
  rolling_window: 3 # number of previous intervals to consider for rolling statistics
  min_replicas: 1
  max_replicas: 3
  features:
    - "age_at_session"
    - "dialysis_vintage_years"
    - "fluid_to_remove"
    - "minutes_into_session"
    - "gender"
    - "DM"
    - "avg_sbp"
    - "min_sbp"
    - "stddev_sbp"
    - "avg_dbp"
    - "avg_dia_temp"
    - "avg_conductivity"
    - "avg_uf_rate"
    - "avg_blood_flow"
    - "lag_1_avg_sbp"
    - "trend_1_sbp"
    - "lag_1_avg_uf_rate"
    - "trend_1_conductivity"
    - "rolling_avg_sbp"
    - "rolling_max_sbp"
    - "rolling_stddev_sbp"
